# Generated by Django 5.1.1 on 2024-10-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0002_alter_fileupload_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
