# Generated by Django 5.1.1 on 2024-10-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drive", "0003_alter_fileupload_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fileupload",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file",
            field=models.FileField(upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
